name: cofeenator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  bloc: ^9.2.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  http: ^1.6.0
  line_icons: ^2.0.3
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
